[workspace]
members = [
    "xtask",
    "apps/helloworld",
    "apps/blink",
    "libs/_pre-main",
    "libs/stdio",
    "libs/led",
    "ports/_interface",
    "ports/_port-impl-export",
    "ports/qemu-virt",
    "ports/ch32v307",
]