[package]
name = "port-impl-export"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qemu-virt = {path="../qemu-virt"}
ch32v307 = {path="../ch32v307"}
interface = {path="../_interface"}